# Generated by Django 4.1.3 on 2022-11-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='passwd',
            field=models.CharField(max_length=16),
        ),
    ]
