# Generated by Django 4.1.3 on 2022-11-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_alter_userinfo_passwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='passwd',
            field=models.CharField(max_length=32),
        ),
    ]
