# Generated by Django 4.1.3 on 2022-11-16 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_alter_userinfo_passwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='register',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
