# Generated by Django 4.1.3 on 2022-11-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_userinfo_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='expiry',
            field=models.DateField(auto_now=True, verbose_name='到期时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=32),
        ),
    ]
