# Generated by Django 4.1.3 on 2022-11-16 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_alter_userinfo_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last',
            field=models.DateField(auto_now=True, verbose_name='最后登录时间'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='usedmonth',
            field=models.IntegerField(default=0, verbose_name='月使用量'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='usedyears',
            field=models.IntegerField(default=0, verbose_name='年使用量'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='who',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(max_length=32, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='passwd',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='register',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
    ]
