# Generated by Django 4.1.3 on 2022-11-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_userinfo_last_userinfo_usedmonth_userinfo_usedyears_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='expiry',
            field=models.DateField(blank=True, null=True, verbose_name='到期时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='who',
            field=models.CharField(default='hello', max_length=32),
        ),
    ]
