# Generated by Django 4.1.3 on 2022-11-17 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_alter_userinfo_expiry_alter_userinfo_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='register',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='注册时间'),
        ),
    ]
