# Generated by Django 4.1.3 on 2022-11-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_alter_userinfo_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='register',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
    ]
