# Generated by Django 4.1.3 on 2022-11-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_alter_userinfo_email_alter_userinfo_passwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='passwd',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='eemail',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='epasswd',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='密码'),
        ),
    ]
