# Generated by Django 4.1.3 on 2022-11-17 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0012_remove_userinfo_email_remove_userinfo_passwd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='eemail',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='epasswd',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='passwd',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='expiry',
            field=models.DateField(default=datetime.date(2022, 11, 24), verbose_name='到期时间'),
        ),
    ]
