# Generated by Django 4.1.3 on 2022-11-19 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_alter_userinfo_email_alter_userinfo_passwd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='register',
            new_name='registerTime',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='usedmonth',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='usedyears',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='registerIP',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='注册ip'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='usedDownMonth',
            field=models.IntegerField(default=0, verbose_name='月下行使用量'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='usedDownYear',
            field=models.IntegerField(default=0, verbose_name='年下行使用量'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='usedUpMonth',
            field=models.IntegerField(default=0, verbose_name='月上行使用量'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='usedUpYear',
            field=models.IntegerField(default=0, verbose_name='年上行使用量'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='expiry',
            field=models.DateField(default=datetime.date(2022, 11, 26), verbose_name='到期时间'),
        ),
    ]
