# Generated by Django 4.1.3 on 2022-11-30 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0016_rename_register_userinfo_registertime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='dirty',
            field=models.SmallIntegerField(default=0, verbose_name='处理'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='expiry',
            field=models.DateField(default=datetime.date(2022, 12, 7), verbose_name='到期时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_uuid',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='uuid'),
        ),
    ]
